export { classifyObjectives } from './objectives/classify'
export { generateFormations } from './placement/formations'
export { isLegalPlacement } from './placement/legal-check'
export { scorePosition } from './placement/scoring'
export { solveDeployment } from './solver'
export { generateThreatMap } from './threats/threat-map'
export * from './types'
export { computeDropOrder } from './units/drop-order'
export { assignRoles } from './units/role-assignment'
export { computeDeploymentZone, computeEnemyZone } from './zones/deployment-zones'
